package com.example.danilo.testingmap;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexRangeKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

/**
 * Created by Danilo on 2016-07-22.
 */
@DynamoDBTable(tableName = "fooddelivery-mobilehub-1629399668-Drivers")
public class Driverdb {


    private String userId;
    private String firstName;
    private String lastName;
    private String email;
    private String uid;
    private String fid;
    private Boolean verified;
    private String plate;
    private String carModel;
    private String brandofCar;
    private String createdAt;
    private String address;
    private String phoneNum;


    public Driverdb()
    {

    }
    @DynamoDBAttribute(attributeName = "Address")
    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }
    @DynamoDBAttribute(attributeName = "PhoneNum")
    public String getPhoneNum() {
        return phoneNum;
    }

    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum;
    }
    @DynamoDBAttribute(attributeName = "Verified")
    public Boolean getVerified() {
        return verified;
    }

    public void setVerified(Boolean verified) {
        this.verified = verified;
    }

    @DynamoDBAttribute(attributeName = "Plate")
    public String getPlate() {
        return plate;
    }

    public void setPlate(String plate) {
        this.plate = plate;
    }

    @DynamoDBAttribute(attributeName = "ModelofCar")
    public String getCarModel() {
        return carModel;
    }

    public void setCarModel(String carModel) {
        this.carModel = carModel;
    }

    @DynamoDBAttribute(attributeName = "BrandofCar")
    public String getBrandofCar() {
        return brandofCar;
    }

    public void setBrandofCar(String brandofCar) {
        this.brandofCar = brandofCar;
    }




    @DynamoDBHashKey(attributeName = "userId")
    @DynamoDBAutoGeneratedKey
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @DynamoDBAttribute(attributeName = "FirstName")
    public String getFirstName() {
        return firstName;
    }

    @DynamoDBAttribute(attributeName = "LastName")
    public String getLastName() {
        return lastName;
    }

    @DynamoDBIndexHashKey(attributeName = "Email", globalSecondaryIndexName = "Email-UID-index-Drivers")
    public String getEmail() {
        return email;
    }

    @DynamoDBIndexRangeKey(attributeName = "UID", globalSecondaryIndexName = "Email-UID-index-Drivers")
    public String getUid() {
        return uid;
    }

    @DynamoDBAttribute(attributeName = "Fid")
    public String getFid() {
        return fid;
    }

    public void setFid(String fid) {
        this.fid = fid;
    }


    @DynamoDBAttribute(attributeName = "Created_At")
    public String getCreatedAt() {
        return createdAt;
    }




    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }


    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }
}
