package com.example.danilo.testingmap;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexRangeKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

/**
 * Created by Danilo on 2016-08-30.
 */
@DynamoDBTable(tableName = "fooddelivery-mobilehub-1629399668-Orders")
public class ordersDB {



    private String orderId;
    private String CustomerName;
    private String Email;
    private String PlaceToGo;
    private String City;
    private String PostalCode;
    private String Country;
    private String province;
    private String FullAddress;
    private String WhatTheyWant;
    private String CREATED_AT;
    private String custFID;
    private String DriverID;
    private String Status;

    public String getTotal() {
        return Total;
    }

    public void setTotal(String total) {
        Total = total;
    }

    private String Total;

    @DynamoDBIndexRangeKey(attributeName = "DriverID", globalSecondaryIndexName = "DriveID")
    public String getDriverID() {
        return DriverID;
    }

    public void setDriverID(String driverID) {
        DriverID = driverID;
    }



    @DynamoDBAttribute(attributeName = "status")
    public String getStatus() {
        return Status;
    }

    public void setStatus(String status) {
        Status = status;
    }



    public ordersDB() {
    }

    @DynamoDBHashKey(attributeName = "orderId")
    @DynamoDBAutoGeneratedKey
    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    @DynamoDBAttribute(attributeName = "CustomerName")
    public String getCustomerName() {
        return CustomerName;
    }

    public void setCustomerName(String customerName) {
        CustomerName = customerName;
    }

    @DynamoDBAttribute(attributeName = "Email")
    public String getEmail() {
        return Email;
    }

    public void setEmail(String email) {
        Email = email;
    }

    @DynamoDBAttribute(attributeName = "PlacesToGo")
    public String getPlaceToGo() {
        return PlaceToGo;
    }

    public void setPlaceToGo(String placeToGo) {
        PlaceToGo = placeToGo;
    }

    @DynamoDBIndexRangeKey(attributeName = "City", globalSecondaryIndexName = "State-City-index-Orders")
    public String getCity() {
        return City;
    }
    public void setCity(String city) {
        City = city;
    }

    @DynamoDBAttribute(attributeName = "PostalCode")
    public String getPostalCode() {
        return PostalCode;
    }

    public void setPostalCode(String postalCode) {
        PostalCode = postalCode;
    }

    @DynamoDBIndexHashKey(attributeName = "State", globalSecondaryIndexName = "State-City-index-Orders")
    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }
    @DynamoDBAttribute(attributeName = "Country")
    public String getCountry() {
        return Country;
    }

    public void setCountry(String country) {
        Country = country;
    }

    @DynamoDBAttribute(attributeName = "FullAddress")
    public String getFullAddress() {
        return FullAddress;
    }

    public void setFullAddress(String fullAddress) {
        FullAddress = fullAddress;
    }

    @DynamoDBAttribute(attributeName = "WhatTheyWant")
    public String getWhatTheyWant() {
        return WhatTheyWant;
    }

    public void setWhatTheyWant(String whatTheyWant) {
        WhatTheyWant = whatTheyWant;
    }

    @DynamoDBAttribute(attributeName = "CreatedAt")
    public String getCREATED_AT() {
        return CREATED_AT;
    }

    public void setCREATED_AT(String CREATED_AT) {
        this.CREATED_AT = CREATED_AT;
    }

    @DynamoDBAttribute(attributeName = "CustFID")
    public String getCustFID() {
        return custFID;
    }

    public void setCustFID(String custFID) {
        this.custFID = custFID;
    }

}
